<?php
   return [
    'COMPANY_NAME' => 'WebArt Technology',
    'EMAIL_ERROR' => 'Please enter a registered Email ID',
    'DUPLICATE_EMAIL_ID' => 'You entered a duplicate Email ID',
    'PASSWORD_ERROR' => 'Password does not match',
    'ADD_SUCCESS' => 'Data has been added successfully',
    'ADD_ERROR' => 'Data added error',
    'UPDATE_SUCCESS' => 'Data has been updated successfully',
    'UPDATE_ERROR' => 'Data update error or you have no change',
    'DELETE_SUCCESS' => 'Data has been deleted successfully',
    'DELETE_ERROR' => 'Data Deleted error',
    'METHOD_ERROR' => 'Unknown Method',
    'VERIFICATION_SUCCESS' => 'We have send a verification code to your Email ID.',
    'OLD_PASSWORD_ERROR' => 'Your old Password does not match',
    'PASSWORD_CHANGE_ERROR' => 'Password changed unsuccessful',
    'PASSWORD_CHANGE_SUCCESS' => 'Password has been changed successfully',
    'PASSWORD_CONFIRM_ERROR' => 'New Password and Confirm Password does not match',
    'BLOG_ADD_SUCCESS' => 'Blogs Data has been added successfully',
    'BLOG_ADD_ERROR' => 'Blogs Data add unsuccessful',
    'BLOG_TITLE_DUPLICATE_ERROR' => 'Blog Title already exists',
    'BLOG_UPDATE_ERROR' => 'Blogs Data update unsuccessfull',
    'BLOG_UPDATE_SUCCESS' => 'Blogs Data has been updated successfully',
    'SUBCATEGORY_DUPLICATE_ERROR' => 'Subcategory already exists',
    'CATEGORY_DUPLICATE_ERROR' => 'Category already exists',
    'CATEGORY_ADD_SUCCESS' => 'Category has been added successfully',
    'CATEGORY_ADD_ERROR' => 'Category add unsuccessful',
    'CATEGORY_UPDATE_ERROR' => 'Category update unsuccessfull',
    'CATEGORY_UPDATE_SUCCESS' => 'Category has been updated successfully',
    ];
?>